version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker-compose up --abort-on-container-exit --exit-code-from e2e
workflows:
  build:
    jobs:
    - build
  version: 2
