version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    # - setup_remote_docker
    - run: docker-compose up --abort-on-container-exit --exit-code-from e2e
    # - restore_cache:
    #     keys:
    #     - cache-{{ .Branch }}-{{ checksum "package.json" }}
    # - run:
    #     name: Npm CI
    #     command: npm ci
    # - run:
    #     command: npx cypress verify
    # - save_cache:
    #     key: cache-{{ .Branch }}-{{ checksum "package.json" }}
    #     paths:
    #     - ~/.npm
    #     - ~/.cache
    # - persist_to_workspace:
    #     root: ~/
    #     paths:
    #     - project
    #     - .cache/Cypress
    # - attach_workspace:
    #     at: ~/
    # - run:
    #     name: Start Python server
    #     command: python -m SimpleHTTPServer 8000
    #     background: true
    # - run:
    #     name: Run Cypress tests
    #     command: 'npx cypress run'
workflows:
  build:
    jobs:
    - build
  version: 2
