version: '3'
services:
  web:
    image: apache
    build: ./webapp
    container_name: apache
    restart: always
    ports:
      - "8080:80"

  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web"
    # so "curl http://web" would return whatever the webserver
    # in the "web" container is cooking
    environment:
      - CYPRESS_baseUrl=http://web
    command: npx cypress run
