version: '3'

tasks:
  npm_up:
    desc: install npm dependencies
    cmds:
      - npm ci # install dependencies
#      - npm audit fix
#      - npm start # start server on port 8080
      - npx cypress open # for headed interactive mode
  
  npm_check_proxy:
    desc: kollar proxy inställningar
    cmds:
      - npm config get proxy
      - npm config get https-proxy
  
  cypress-docker:
    cmds:
      - docker run -it -v ${PWD}:/e2e -w /e2e cypress/included:latest npx cypress run


#  up:
#    dir: '{{.USER_WORKING_DIR}}'
#    preconditions:
#      - test -f docker-compose.yml
#    cmds:
#      - docker-compose up -d